# 轻量级 CI 工作流：仅运行快速单元与冒烟测试。
name: Lightweight CI
# 触发条件：对任意分支的 push 以及所有 Pull Request。
on:
  # Push 事件覆盖主干与特性分支，保持快速反馈。
  push:
  # Pull Request 事件确保合并前也会执行校验。
  pull_request:
# 定义作业列表，此处仅包含一个 pytest 任务。
jobs:
  tests:
    # 说明运行环境，选择 ubuntu-latest 以获得最快启动时间。
    runs-on: ubuntu-latest
    # 可选矩阵留作扩展示例，通过注释解释如何拓展平台。
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest]
    #   runs-on: ${{ matrix.os }}
    # 作业步骤按顺序执行。
    steps:
      # 第一步：签出仓库代码。
      - name: Checkout repository
        uses: actions/checkout@v4
      # 第二步：安装 Python 3.10，版本与本地开发保持一致。
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # 第三步：安装开发与测试依赖，仅使用 requirements-dev.txt。
      - name: Install test dependencies
        run: pip install -r requirements-dev.txt
      # 第四步：运行 pytest，使用 -q 保持输出精简，--maxfail=1 加速失败反馈。
      - name: Run pytest
        run: pytest -q --maxfail=1
